### ISSUE TITLE
Possible bug with translations?

### ISSUE THREAD

**Issue by nemrutco** [dillingham/nova-items-field#12]
I am trying to make translatable field using this package. But i couldn't figure out a way to do it. I am keep getting Array to string conversion error. Anyone can tell me a way?

```php
// Model
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class MapInfo extends Model
{
    use HasTranslations;

    public $translatable =  ['title', 'info'];
    public $casts = [
        'info' => 'array'
    ];
}
``` 
```php
// Nova Resource Fields
...
 public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Translatable::make([
                Text::make(__('Title')),
                Items::make(__('Info'))
            ]),
        ];
    }
```
```php
// Observer
namespace App\Observers;

use App\MapInfo;
use Illuminate\Support\Facades\Log;

class MapInfoObserver
{
....
    function saving(MapInfo $mapinfo)
    {
        // not sure what to do here so i log and see the output
        Log::info($mapinfo);
    }
```

```php
// Log file
[2019-09-08 05:30:03] local.INFO: {"title":{"en":"asd","zh-cn":"asd"},"translations_info_en":[],"translations_info_zh-cn":[],"floor_id":1}  
[2019-09-08 05:30:03] local.ERROR: Array to string conversion {"userId":1,"exception":"[object] (ErrorException(code: 0): Array to string conversion at /Users/muzafferdede/Desktop/Code/dts/vendor/laravel/framework/src/Illuminate/Support/Str.php:353)
[stacktrace]
#0 /Users/muzafferdede/Desktop/Code/dts/vendor/laravel/framework/src/Illuminate/Support/Str.php(353): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '/Users/muzaffer...', 353, Array)
#1 /Users/muzafferdede/Desktop/Code/dts/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(56): Illuminate\\Support\\Str::replaceArray('?', Array, 'insert into `ma...')
#....
```
i believe it is something simple but i am too tired to find it out all night, please help :(

**Comment by cgarofalo** [comment]
I am having the same issue. *bump*

**Comment by dillingham** [comment]
Seems like an issue you should open on the `Translatable` field
Not sure what my package can do to make that package translate array fields
